version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/apps/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/apps/api/src/Monorepo.Api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
