/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWeatherForecastRouteImport } from './routes/_app/weather-forecast'

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWeatherForecastRoute = AppWeatherForecastRouteImport.update({
  id: '/_app/weather-forecast',
  path: '/weather-forecast',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/weather-forecast': typeof AppWeatherForecastRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/weather-forecast': typeof AppWeatherForecastRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/weather-forecast': typeof AppWeatherForecastRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/weather-forecast' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/weather-forecast' | '/'
  id: '__root__' | '/_app/weather-forecast' | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppWeatherForecastRoute: typeof AppWeatherForecastRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/weather-forecast': {
      id: '/_app/weather-forecast'
      path: '/weather-forecast'
      fullPath: '/weather-forecast'
      preLoaderRoute: typeof AppWeatherForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppWeatherForecastRoute: AppWeatherForecastRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
